OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Bank
    Domain: bank.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Police
    Domain: police.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
