# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.bank.example.com:
    container_name: peer0.bank.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank.example.com
      - CORE_PEER_ADDRESS=peer0.bank.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.police.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.example.com:7051
      - CORE_PEER_LOCALMSPID=BankMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.bank.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.police.example.com:
    container_name: peer0.police.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.police.example.com
      - CORE_PEER_ADDRESS=peer0.police.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.police.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.police.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank.example.com:9051
      - CORE_PEER_LOCALMSPID=PoliceMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/police.example.com/peers/peer0.police.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.police.example.com:/var/hyperledger/production
    ports:
      - 9051:9051

  caBank:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6da3e6a643ce28bea9b27d0c85357afcd2f87cf68fa117e51d044f1a4eb07452_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - '7054:7054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bank.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6da3e6a643ce28bea9b27d0c85357afcd2f87cf68fa117e51d044f1a4eb07452_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/bank.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  caPolice:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-police
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.police.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2873f3bcd7b93371491d5f19cbc670156025cc056a1045e7a923cf55456e7cb0_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - '8054:8054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.police.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2873f3bcd7b93371491d5f19cbc670156025cc056a1045e7a923cf55456e7cb0_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/police.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
