# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.bank.example.com:
    container_name: peer0.bank.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank.example.com
      - CORE_PEER_ADDRESS=peer0.bank.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.police.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.example.com:7051
      - CORE_PEER_LOCALMSPID=BankMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/bank.example.com/peers/peer0.bank.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.bank.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.police.example.com:
    container_name: peer0.police.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.police.example.com
      - CORE_PEER_ADDRESS=peer0.police.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.police.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.police.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank.example.com:9051
      - CORE_PEER_LOCALMSPID=PoliceMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/police.example.com/peers/peer0.police.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/police.example.com/peers/peer0.police.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.police.example.com:/var/hyperledger/production
    ports:
      - 9051:9051

  caBank:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6cc6ac6aa39fe0dd7dd818c9f94049febd3832e2815dddfd600f2e34b59151e3_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - '7054:7054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bank.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6cc6ac6aa39fe0dd7dd818c9f94049febd3832e2815dddfd600f2e34b59151e3_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/bank.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  caPolice:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-police
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.police.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e26f23169e94ed6b605bd1d9209731ff591948993bb17dfd7b6bcda7eec096c9_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - '9054:9054'
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.police.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e26f23169e94ed6b605bd1d9209731ff591948993bb17dfd7b6bcda7eec096c9_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/police.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
